### ISSUE TITLE
New implementations

### ISSUE THREAD

**Issue by cyrusmsk** [Axect/Scientific_Bench#1]
Hello.

Will you make reruns and approve PR with other implementations?

**Comment by Axect** [comment]
Hello @cyrusmsk 

Thank you for your question!
Yes, we're happy to review and approve PRs with alternative implementations.
As long as the implementation is reasonably well-designed and meets the project's standards, we welcome such contributions.

Feel free to submit your implementation and we'll review it.

**Comment by cyrusmsk** [comment]
Thanks.
Currently I'm almost finished with Basic example.
Can you please confirm for this task you assume that the code will be single threaded?

Because I'm not sure if I can use multi-core capabilities
